services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=s3,lambda,apigateway,ssm,sts,dynamodb,cloudformation, iam, ec2
      - DEFAULT_REGION=us-east-1
      - DATA_DIR=/tmp/localstack/data
      - TMPDIR=/var/localstack-tmp
    volumes:
      - localstack_tmp:/var/localstack-tmp
      - "/var/run/docker.sock:/var/run/docker.sock"

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  localstack_tmp: